name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  gh_token:
    description:
      Github access token. In the future, we should be able to create one in the
      action.
    required: true

runs:
  using: node20
  main: dist/index.js
