name: PR Comment

on:
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@h2ogpte'))
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
